import React from "react";
import { ForceGraph3D } from "react-force-graph";

const links = [
  { source: "BFDURL", target: "BFLRDU" },
  { source: "BFDURL", target: "DUFBRL" },
  { source: "BFDURL", target: "LRDUBF" },
  { source: "BFLRDU", target: "BFUDLR" },
  { source: "BFLRDU", target: "LRFBDU" },
  { source: "BFLRDU", target: "UDLRBF" },
  { source: "BFRLUD", target: "BFDURL" },
  { source: "BFRLUD", target: "DURLBF" },
  { source: "BFRLUD", target: "RLFBUD" },
  { source: "BFUDLR", target: "BFRLUD" },
  { source: "BFUDLR", target: "RLUDBF" },
  { source: "BFUDLR", target: "UDFBLR" },
  { source: "DUBFLR", target: "BFUDLR" },
  { source: "DUBFLR", target: "DURLBF" },
  { source: "DUBFLR", target: "RLBFDU" },
  { source: "DUFBRL", target: "DULRFB" },
  { source: "DUFBRL", target: "FBUDRL" },
  { source: "DUFBRL", target: "LRFBDU" },
  { source: "DULRFB", target: "BFLRDU" },
  { source: "DULRFB", target: "DUBFLR" },
  { source: "DULRFB", target: "LRUDFB" },
  { source: "DURLBF", target: "DUFBRL" },
  { source: "DURLBF", target: "FBRLDU" },
  { source: "DURLBF", target: "RLUDBF" },
  { source: "FBDULR", target: "DUBFLR" },
  { source: "FBDULR", target: "FBRLDU" },
  { source: "FBDULR", target: "RLDUFB" },
  { source: "FBLRUD", target: "DULRFB" },
  { source: "FBLRUD", target: "FBDULR" },
  { source: "FBLRUD", target: "LRBFUD" },
  { source: "FBRLDU", target: "FBUDRL" },
  { source: "FBRLDU", target: "RLBFDU" },
  { source: "FBRLDU", target: "UDRLFB" },
  { source: "FBUDRL", target: "FBLRUD" },
  { source: "FBUDRL", target: "LRUDFB" },
  { source: "FBUDRL", target: "UDBFRL" },
  { source: "LRBFUD", target: "BFRLUD" },
  { source: "LRBFUD", target: "DUBFLR" },
  { source: "LRBFUD", target: "LRDUBF" },
  { source: "LRDUBF", target: "DURLBF" },
  { source: "LRDUBF", target: "FBDULR" },
  { source: "LRDUBF", target: "LRFBDU" },
  { source: "LRFBDU", target: "FBRLDU" },
  { source: "LRFBDU", target: "LRUDFB" },
  { source: "LRFBDU", target: "UDFBLR" },
  { source: "LRUDFB", target: "BFUDLR" },
  { source: "LRUDFB", target: "LRBFUD" },
  { source: "LRUDFB", target: "UDRLFB" },
  { source: "RLBFDU", target: "BFLRDU" },
  { source: "RLBFDU", target: "RLUDBF" },
  { source: "RLBFDU", target: "UDBFRL" },
  { source: "RLDUFB", target: "BFDURL" },
  { source: "RLDUFB", target: "DULRFB" },
  { source: "RLDUFB", target: "RLBFDU" },
  { source: "RLFBUD", target: "DUFBRL" },
  { source: "RLFBUD", target: "FBLRUD" },
  { source: "RLFBUD", target: "RLDUFB" },
  { source: "RLUDBF", target: "FBUDRL" },
  { source: "RLUDBF", target: "RLFBUD" },
  { source: "RLUDBF", target: "UDLRBF" },
  { source: "UDBFRL", target: "BFDURL" },
  { source: "UDBFRL", target: "LRBFUD" },
  { source: "UDBFRL", target: "UDLRBF" },
  { source: "UDFBLR", target: "FBDULR" },
  { source: "UDFBLR", target: "RLFBUD" },
  { source: "UDFBLR", target: "UDRLFB" },
  { source: "UDLRBF", target: "FBLRUD" },
  { source: "UDLRBF", target: "LRDUBF" },
  { source: "UDLRBF", target: "UDFBLR" },
  { source: "UDRLFB", target: "BFRLUD" },
  { source: "UDRLFB", target: "RLDUFB" },
  { source: "UDRLFB", target: "UDBFRL" },
]
let nodes = [
  { id: "BFDURL"},
  { id: "BFLRDU"},
  { id: "BFRLUD"},
  { id: "BFUDLR"},
  { id: "DUBFLR"},
  { id: "DUFBRL"},
  { id: "DULRFB"},
  { id: "DURLBF"},
  { id: "FBDULR"},
  { id: "FBLRUD"},
  { id: "FBRLDU"},
  { id: "FBUDRL"},
  { id: "LRBFUD"},
  { id: "LRDUBF"},
  { id: "LRFBDU"},
  { id: "LRUDFB"},
  { id: "RLBFDU"},
  { id: "RLDUFB"},
  { id: "RLFBUD"},
  { id: "RLUDBF"},
  { id: "UDBFRL"},
  { id: "UDFBLR"},
  { id: "UDLRBF"},
  { id: "UDRLFB"},
];

const GraphComponent = () => {
  const data = {
    nodes: nodes, //[{ id: "A" }, { id: "B" }, { id: "C" }],
    links: links, //[
  };

  return <ForceGraph3D graphData={data} />;
};




export default GraphComponent;
